trigger:
- '*'

jobs:
  #Run the Build and Test Job along with other scans
  - template: CredScan/jobs/Build_Test-1.yml
    parameters:
     Pool: 'windows-latest'
     buildConfiguration: 'Release'
     buildPlatform: 'any cpu'
