trigger:
- '*'

jobs:
  #Run the Build and Test Job along with other scans
  - template: CredScan/jobs/Build_Test-1.yml
    parameters:
     Pool: 'windows-latest'
     buildConfiguration: 'Release'
     buildPlatform: 'any cpu'

  #Run Credentail Scan Job
  - template: CredScan/jobs/CredScan-1.yml
    parameters:
     Pool: 'windows-latest'

  #Run Credentail Scan Job with customer searchers
  - template: CredScan/jobs/CredScan-custom-searchers.yml
    parameters:
     Pool: 'windows-latest'
     searchersFile: 'CredScan/searchers/buildsearcher.xml'     
  
  - template: CredScan/jobs/CredScan-truffleHog-1.yml
    parameters:
      Pool: 'ubuntu-latest'   