parameters:
  Pool: ''

jobs:
  - job: CredScan_credential_digger_Job
    displayName: 'Use credentail digger for Credential Scanning'
    pool:
      vmImage: ${{ parameters.Pool }}
    steps:
    - bash: |
        PATH="$PATH:$HOME/.local/bin"
        sudo apt install -y libhyperscan-dev build-essential python3-dev
        pip install credentialdigger
        python -m credentialdigger add_rules --sqlite data.db CredScan/scan-rules/credential-digger-rules.yml
        python -m credentialdigger scan https://github.com/fsaleemm/DevSecOps --sqlite data.db
        sqlite3 data.db << 'EOF_SQL' 
        .header on
        .mode column
        SELECT * FROM discoveries join rules on discoveries.rule_id = rules.id;
        EOF_SQL
      displayName: 'Install credential digger and Scan'